const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Car,
		C3.Behaviors.custom,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Plugins.Camera3D,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Sprite.Exps.Z,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.custom.Acts.PushOutSolidAngle,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Shape3D.Acts.SetZ,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Camera3D.Exps.CameraYRotation,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Destroy
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Car: 0},
	{Custom: 0},
	{Player: 0},
	{TiledBackground: 0},
	{"3DShape": 0},
	{"3DCamera": 0},
	{Keyboard: 0},
	{Mouse: 0},
	{zAxis: 0},
	{speed: 0},
	{Bullet: 0},
	{MoveTo: 0},
	{Enemy: 0},
	{spawn_enemy: 0},
	{PlayerHeight: 0},
	{PlayerSpeed: 0},
	{MouseSpeed: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Bullet: class extends self.I3DShapeInstance {},
	Enemy: class extends self.I3DShapeInstance {},
	spawn_enemy: class extends self.ISpriteInstance {}
}